<a href="https://colab.research.google.com/github/PATELOM925/Deep-Learning-For-Computer-Vision/blob/main/DL4V_Assignment_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **Welcome to Assignment 0 on Deep Learning for Computer Vision.**
In this assignment you will get a chance to understand and work on some of the commonly used functionalities of several Machine Learnign and Data Analysis libraries

#### **Instructions**
1. Use Python 3.x to run this notebook
2. Write your code only in between the lines 'YOUR CODE STARTS HERE' and 'YOUR CODE ENDS HERE'.
3. Look up the documentation for each of the Python and Numpy function used.
4. This Assignment is just to make you understand several commonly used library functions.
5. This assignment is **NOT** evaluated

In [1]:
# DO NOT CHANGE THIS CODE
import numpy as np
np.random.seed(0)

#### Python Basics


In [2]:
### Implement recursive fibonacci in the function below
def recursive_fibonacci(n):
  if n<=0:
    return 0
  elif n==1:
    return 1
  else:
    return recursive_fibonacci(n-2)+recursive_fibonacci(n-1)



In [7]:
### Test your code using the function call below.
recursive_fibonacci(6)

8

#### Lambda function

In [11]:
def sigmoid(x):
  sigmoid = 1 / (1 + np.exp(-x))
  return sigmoid

## Implement the above sigmoid function using python lambda functions
## YOUR CODE STARTS HER
sigmoid_lambda = lambda x: 1 / (1 + np.exp(-x))


In [9]:
## Check you implementation by running this cell (should return True)
sigmoid(1) == sigmoid_lambda(1)

True

#### List Comprehension

In [12]:
div_by_four = []
for number in range(200):
    if number%4 == 0:
        div_by_four.append(number)

## Implement the above function using list comprehensions
## YOUR CODE STARTS HERE
div_by_four_lc = [number for number in range(200) if number%4==0]
## YOUR CODE ENDS HERE

In [13]:
## Check you implementation by running this cell (should return True)
div_by_four == div_by_four_lc

True

#### Python map keyword
Using the lambda functions and python's map keyword apply sigmoid on a list of numbers from 0 to 99. Store the output in a list and print it.

**Observe what happens to the value of sigmoid as the value of x increases. Do you see any trend?**

In [19]:

# the sigmoid lambda function
sigmoid_lambda = lambda x: 1 / (1 + np.exp(-x))

# Create a list of numbers from 0 to 99
numbers = list(range(100))

# Using map to Apply sigmoid to the list of numbers
sigmoid_values = list(map(sigmoid_lambda, numbers))

# Printing sigmoid values
print(sigmoid_values)

# the trend i see in output is a plateau growth  hit by our graph after reaching
# certain value

[0.5, 0.7310585786300049, 0.8807970779778823, 0.9525741268224334, 0.9820137900379085, 0.9933071490757153, 0.9975273768433653, 0.9990889488055994, 0.9996646498695336, 0.9998766054240137, 0.9999546021312976, 0.999983298578152, 0.9999938558253978, 0.999997739675702, 0.9999991684719722, 0.999999694097773, 0.9999998874648379, 0.9999999586006244, 0.9999999847700205, 0.9999999943972036, 0.9999999979388463, 0.9999999992417439, 0.9999999997210531, 0.9999999998973812, 0.9999999999622486, 0.999999999986112, 0.999999999994891, 0.9999999999981204, 0.9999999999993086, 0.9999999999997455, 0.9999999999999065, 0.9999999999999656, 0.9999999999999873, 0.9999999999999953, 0.9999999999999982, 0.9999999999999993, 0.9999999999999998, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

# Numpy Basics:


#### Creating a numpy array with particular value


In [23]:
# Create a numpy array with size 2*2 with all elements as 8.

# YOUR CODE STARTS HERE
arr = np.full((2,2),8)
print(arr)
# YOUR CODE ENDS HERE

[[8 8]
 [8 8]]


#### Basic Numpy operations:

In [25]:
#Create a numpy array of size 3*3 with random values

#YOUR CODE STARTS HERE
rand_arr = np.random.rand(3,3)
print(rand_arr)
#YOUR CODE ENDS HERE



[[0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]]


In [28]:
#Find the sum of all the elements, mean, maximum and minimum value of the numpy array defined above

#YOUR CODE STARTS HERE
arr_sum = np.sum(rand_arr)
arr_mean = np.mean(rand_arr)
arr_max = np.max(rand_arr)
arr_min = np.min(rand_arr)
#YOUR CODE ENDS HERE

print("Sum of elements:", arr_sum)
print("Mean value:", arr_mean)
print("Maximum value:", arr_max)
print("Minimum value:", arr_min)

Sum of elements: 4.208706276935631
Mean value: 0.4676340307706257
Maximum value: 0.925596638292661
Minimum value: 0.02021839744032572


#### Reshaping and Indexing of Numpy Array:

In [31]:
#create a 1D numpy array of shape 35 with values 1,2,3..,35

#YOUR CODE STARTS HERE
y = np.arange(1,36)
print(y)
#YOUR CODE ENDS HERE

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


In [33]:
# Reshape it as 2D array of shape (5,7)
y1 = np.arange(1,36)
print(y1)
#YOUR CODE STARTS HERE
y2 =  y1.reshape(5,7)
#YOUR CODE ENDS HERE
y2.shape
print(y2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]


In [35]:
# Extract all the elements from 2nd and 3rd row

#YOUR CODE STARTS HERE

row3 = y2[3,:]
row4 = y2[4,:]

print("3rd row: ",row3)
print("4th row: ",row4)
#YOUR CODE ENDS HERE

3rd row:  [22 23 24 25 26 27 28]
4th row:  [29 30 31 32 33 34 35]


In [39]:
# Extract all the elements from 3rd and 5th and 7th column

#YOUR CODE STARTS HERE
col3 = y2[:,2]
col7 = y2[:,6]
col5 = y2[:,4]

print("3rd column: ",col3)
print("5rd column: ",col5)
print("7rd column: ",col7)

#YOUR CODE ENDS HERE

3rd column:  [ 3 10 17 24 31]
5rd column:  [ 5 12 19 26 33]
7rd column:  [ 7 14 21 28 35]


#### Horizontal and vertical stacking of numpy array

In [44]:
## horizontal and vertical stacking of 1D arrays
a = np.array([4,2])
b = np.array([3,8])

print(a)
print(b)

#YOUR CODE STARTS HERE
# Horizontal stacking
h_stack = np.hstack((a,b))
print("horrizontal stack ",h_stack)

# Vertical Stacking
v_stack = np.vstack((a,b))
#YOUR CODE ENDS HERE
print("Vertical Stack ",v_stack)

[4 2]
[3 8]
horrizontal stack  [4 2 3 8]
Vertical Stack  [[4 2]
 [3 8]]


#### `argmin` and `argmax` in numpy array

In [47]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])

# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
max_idx = np.unravel_index(np.argmax(arr),arr.shape)
min_idx = np.unravel_index(np.argmin(arr),arr.shape)
print("max id ",max_idx)
print("min id ",min_idx)

#Find the indices of maximum and minimum value along each of its columns.
max_col = np.argmax(arr,axis=0)
min_col = np.argmin(arr,axis=0)
print("max id ",max_col)
print("min id ",min_col)
#Find the indices of maximum and minimum value along each of the its rows.
max_row = np.argmax(arr,axis=1)
min_row = np.argmin(arr,axis=1)
print("max id ",max_row)
print("min id ",min_row)
#YOUR CODE ENDS HERE

max id  (0, 2)
min id  (1, 2)
max id  [1 1 0 1]
min id  [0 0 1 0]
max id  [2 1]
min id  [0 2]
